version: '3.8'

services:
  tg-ws-proxy:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        USERNAME: ${USERNAME}
        PASSWORD: ${PASSWORD}
    container_name: tg-ws-proxy
    ports:
      - "0.0.0.0:1080:1080"
    restart: unless-stopped
