version: '3.8'

services:
  tg-ws-proxy:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: tg-ws-proxy
    environment:
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
    ports:
      - "0.0.0.0:${SOCKS_PORT}:1080"
    restart: unless-stopped
